# Generated by Django 4.0.3 on 2022-08-04 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EmployeData',
            new_name='EmployeeData',
        ),
    ]
