# Generated by Django 4.0.3 on 2022-08-04 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_rename_employedata_employeedata'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('product_id', models.CharField(max_length=200)),
                ('slug_id', models.SlugField(blank=True, null=True)),
                ('manufacture_date', models.DateField(auto_now=True)),
            ],
        ),
    ]
