# Generated by Django 4.0.3 on 2022-08-04 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_productdata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeedata',
            old_name='emplyoee_id',
            new_name='employee_id',
        ),
    ]
